slogan: "文章列表"

theme: flatly
inverse: inverse

menu:
  - title: 归档
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"

  - title: 关于
    url: about
    intro: "About me."
    icon: "fa fa-user"
    
  - title: RSS
    url: atom.xml
    intro: "Feed"
    icon: "fa fa"

links:
  - title: "Github"
    url: https://github.com/HujiangTechnology
    intro: "Github"
   # icon: "fa fa-github"
  - title: "沪江"
    url: http://www.hujiang.com
    intro: "沪江网"
   # icon: "favicon.png"

widgets:
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: https://avatars3.githubusercontent.com/u/13547892?v=3&s=200
duoshuo_shortname: hujiangios

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: false
jiathis: true

