categories: Categories
links: Links
search: Search
tags: Tags
tagcloud: "Tag Cloud"
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: "Page %d"
recent_posts: "Recent Posts"
description: Description
read_more: "Read More"
home: Home
author: author